### ISSUE TITLE
Conflict: Createsuperuser and Profile models.

### ISSUE THREAD

**Issue by aidar31** [Jaswine/Code-Cources-Platform#2]
Незнаю, просто странно что если создать superuser, и попробовать посмотреть профиль, то выдаст ошибку DoesNotExist at /profile. Однако если попробовать зарегистрировать через форму, то мы не сможем использовать username как у админа, хотя у него же нет профиля.

Можно попробовать через def save(), создавать для админа профиль тоже =)

**Comment by Jaswine** [comment]
> Незнаю, просто странно что если создать superuser, и попробовать посмотреть профиль, то выдаст ошибку DoesNotExist at /profile. Однако если попробовать зарегистрировать через форму, то мы не сможем использовать username как у админа, хотя у него же нет профиля.
> 
> Можно попробовать через def save(), создавать для админа профиль тоже =)

ааа, там его нада добавить в админке, через админку, но пожалуй я посмотрюю позже как сделать это через def save

**Comment by Jaswine** [comment]
> 

типо где Profile модель, можно ниче не писать, просто с id создать и все, я не предусмотрел пока автоматическую генерацию модели Profile, когда создается admin

**Comment by Jaswine** [comment]
I did it :]
