### ISSUE TITLE
ValueError at /register/  You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.

### ISSUE THREAD

**Issue by aidar31** [Jaswine/Code-Cources-Platform#8]
При регистрации аккаунта выдает ошибку:
ValueError at /register/

You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.

Вроде как решение добавить аргумент backend="django.contrib.auth.backends.ModelBackend" в login(), но тогда после регистрации все равно не логинит, приходится самому логинится.

Либо добавить в AUTHENTICATION_BACKENDS -> "django.contrib.auth.backends.ModelBackend" .

![изображение](https://user-images.githubusercontent.com/120123042/236669463-647698be-b159-4fc4-bf21-b8bb80797311.png)

**Comment by aidar31** [comment]
И да, у тя комменты в requirements не правильно написаны =)

**Comment by Jaswine** [comment]
оно есть в AUTHENTICATION_BACKENDS = [ "django.contrib.auth.backends.ModelBackend"] , а вот про логин забыл, пасиб, что написал, а то иначе бы узнал бы только через недел две, как миниум
